project:
  type: website
  output-dir: docs

website:
  title: "Ana Paula Goncalves Donate"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About
      - href: research.qmd
        text: Research
      - href: publications.qmd
        text: Publications
      - href: cv.qmd
        text: CV
      - href: contact.qmd
        text: Contact

format:
  html:
    theme: cosmo
    css: styles.css
    toc: false
