---
title: "Publications"
---

## Peer-reviewed manuscripts

Donate, A. P. G., Macedo, E. C. de, Bedendo, A., Félix Júnior, I., Gallo, G. G., Opaleye, E. S., & Noto, A. R. (2023). The effect of mindfulness on decision-making, inhibitory control, and impulsivity of substance use disorder in-treatment patients: A randomized clinical trial. *PLoS ONE, 18*, 1–17. https://doi.org/10.1371/journal.pone.0293502

Donate, A. P. G., Marques, L. M., Lapenta, O. M., Asthana, M. K., Amodio, D., & Boggio, P. S. (2017). Ostracism via virtual chat room—effects on basic needs, anger and pain. *PLOS ONE, 12*, e0184215. https://doi.org/10.1371/journal.pone.0184215

Félix-Junior, I. J., Donate, A. P. G., Noto, A. R., Galduróz, J. C. F., Simionato, N. M., & Opaleye, E. S. (2022). Mindfulness-based interventions in inpatient treatment for substance use disorders: A systematic review. *Addictive Behaviors Reports, 16*, 100467. https://doi.org/10.1016/j.abrep.2022.100467

Gallo, G. G., Curado, D. F., Opaleye, E. S., Donate, A. P. G., Scattone, V. V., & Noto, A. R. (2020). Impulsivity and mindfulness among inpatients with alcohol use disorder. *Substance Use & Misuse, 56*, 25–32. https://doi.org/10.1080/10826084.2020.1833924

José Félix-Junior, I., Sátiro Opaleye, E., Goncalves Donate, A. P., Bedendo, A., Pires, M., Fernandes, C., Bowen, S., & Noto, A. R. (2023). Effectiveness of mindfulness for anger expression on men in treatment for substance use disorders: A randomized controlled trial. *International Journal of Mental Health and Addiction, 23*. https://doi.org/10.1007/s11469-023-01113-y

Manfredi, M., Proverbio, A. M., Gonçalves Donate, A. P., Macarini Gonçalves Vieira, S., Comfort, W. E., De Araújo Andreoli, M., & Boggio, P. S. (2017). tDCS application over the STG improves the ability to recognize and appreciate elements involved in humor processing. *Experimental Brain Research, 235*, 1843–1852. https://doi.org/10.1007/s00221-017-4932-5

## PhD Dissertation

Donate, A. P. G. (2026). *Affective Vulnerability and Health Correlates of Cannabis Use: Insights from Between- and Within-Person Approaches*. PhD Dissertation, Aarhus University, Denmark. [Download PDF](files/APGD_PhD_Dissertation_2026.pdf)

## Preprints

Donate, A. P. G. Cannabis Use, Affect, and Emotion Regulation in Daily Life: A 3-Week Experience Sampling Method Study in People Who Smoke Cannabis Almost Daily. *PsyArXiv Preprints*. https://osf.io/c74ur

Feldstein Ewing, S. W., Dash, G. F., Hudson, K. A., Hyun, B., Yang, M., Stahl, L., Thomsen, K. R., Gonçalves Donate, A. P., & Filbey, F. M. (2025). The protocol for: Do peers enhance alcohol use outcomes in group motivational interviewing? A translational clinical trial investigating brain synchrony in underage emerging adults during a fMRI hyperscanning task and its association with 12-month alcohol use reductions. *medRxiv*. https://doi.org/10.64898/2025.12.10.25341908
